// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  testemonials: dynamic(() => import("./Testemonials")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
